package com.ssafy.gumipresso.common

enum class CONST {
    ACTIVITY_LOGIN, FRAG_LOGIN, FRAG_JOIN, ACTIVITY_MAIN, FRAG_HOME, FRAG_ORDER, FRAG_MYPAGE, FRAG_MAPS, FRAG_NOTI, FRAG_REVIEW_WRITE,
    FRAG_MENU_DETAIL, FRAG_ORDER_DETAIL, FRAG_RECENT_ORDER_DETAIL_FROM_HOME, FRAG_RECENT_ORDER_DETAIL_FROM_MYPAGE,
    FRAG_CART_FROM_ORDER, FRAG_CART_FROM_MYPAGE, FRAG_CART_FROM_RECENT_ORDER_DETAIL, FRAG_CART_TO_HOME,
    LOGOUT

}