package com.ssafy.gumipresso.common

enum class CONST {
    FRAG_LOGIN, FRAG_JOIN, ACTIVITY_MAIN, FRAG_MAPS, FRAG_NOTI, FRAG_REVIEW_WRITE,
    FRAG_ORDER_DETAIL,FRAG_RECENT_ORDER_DETAIL_FROM_MYPAGE,
    FRAG_CART_FROM_ORDER, FRAG_CART_FROM_MYPAGE, FRAG_CART_FROM_RECENT_ORDER_DETAIL,
    LOGOUT, FRAG_GRADE_FROM_MYPAGE, FRAG_SETTING

}